import AboutHero from "<lykdat>/components/AboutHero";
import Navbar from "<lykdat>/components/Navbar";
import Head from "next/head";
const About = () => {
	return ( 
		<>
		<Head>
        <title>LykDat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      	</Head>
		<Navbar/>
		<AboutHero/>
		</>
	 );
}
 
export default About;