import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '<lykdat>/styles/Home.module.css'
import Navbar from '<lykdat>/components/Navbar'
import Banner from '<lykdat>/components/Banner'
import Landing from '<lykdat>/components/Landing'
import Product from '<lykdat>/components/Product'
import Discount from '<lykdat>/components/Discount'
import Sellers from '<lykdat>/components/Sellers'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>
      <Banner/>
      <Landing/>
      <Product title = "Trending Products"/>
      <Discount/>
      <Product title="Vintage Pieces" />
      <Sellers/>
    </>
  )
}
