import Explore from "<lykdat>/components/Explore";
import Feedback from "<lykdat>/components/Feedback";
import Footer from "<lykdat>/components/Footer";
import Navbar from "<lykdat>/components/Navbar";
import Product from "<lykdat>/components/Product";
import { Box, Button } from "@chakra-ui/react";
import Head from "next/head";

const Inspiration = () => {
	return ( 
		<Box>
			<Head>
			<title>LykDat | Explore</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Explore />
			<Product  title="."/>
			<Button>More</Button>
			<Feedback/>
			<Footer/>
		</Box>
	 );
}
 
export default Inspiration;